version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
    - bodyclose
  settings:
    govet:
      enable-all: true
    staticcheck:
      checks: ["all"]
  exclusions:
    paths:
      - vendor
      - .git
      - test
      - third_party

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/peymanahmadi/riskguard